version: "3"

services:
  postgres:
    image: "postgres:16.0"
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: admin 
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: agri
    # volumes:
    #   - ./db-data/user_db_server/:/var/lib/postgresql/data
