#version: "3"

# networks:
#   test:
#     name: fabric_test

# services:
#   ca_org1:
#     image: hyperledger/fabric-ca:latest

#     environment:
#       - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
#       - FABRIC_CA_SERVER_CA_NAME=ca-org1
#       - FABRIC_CA_SERVER_TLS_ENABLED=true
#       - FABRIC_CA_SERVER_PORT=7054
#       - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:17054
#     ports:
#       - "7054:7054"
#       - "17054:17054"
#     command: sh -c 'ls -la /certs/client && sleep 5 && fabric-ca-server start -b admin:adminpw -d'
#     volumes:
#       - ${PWD}/fabric-ca-server/:/etc/hyperledger/fabric-ca-server/
#       - ${PWD}/postgres-certs/client/:/certs/client
#     container_name: ca_org1
#     depends_on:
#       - postgres
#     networks:
#       - test

#   postgres:
#     container_name: postgres
#     image: post:16.0
#     networks:
#       - test
#     ports:
#       - 5433:5432
#     environment:
#       POSTGRES_DB: transaction_service
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres


version: "3"

services:
  transaction_db:
    image: "postgres:16.0"
    container_name: transaction_db
    ports:
      - "5436:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: transaction_db
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: transaction_service
    # volumes:
    #   - ./db-data/catalog_db_server/:/var/lib/postgresql/data