name: Price Prediction Service - Test

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask flask-cors pandas scikit-learn openpyxl pytest

      - name: Set PYTHONPATH
        run: |
          echo "PYTHONPATH=${{ github.workspace }}/back-end/price-prediction-service" >> $GITHUB_ENV

      - name: Start Flask app
        working-directory: back-end/price-prediction-service
        run: |
          python app.py &
          timeout 30 bash -c 'until curl -s http://localhost:3001/health; do sleep 2; done'

      - name: Run tests
        working-directory: back-end/price-prediction-service
        run: pytest test_app.py -v

      - name: Cleanup
        if: always()
        run: pkill -f flask || true